---
title: "Mini-Project 2"
author: "Kalynn Kosyka, Subashini Sridhar, Erina Fukuda"
date: "March 24, 2017"
output: html_document
---


## Loading the data

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r}
candidateContributions<-candidates %>%
  left_join(contributions, by = c("cand_id" = "cand_id"))
  
RomneyContributions <- candidateContributions %>% filter(cand_id == "P80003353", entity_type=="PAC", cand_election_yr == "2012")%>%
  select(-cand_city, -cand_state, -cand_st1,-cand_st2, -cand_office_district, -cand_status, -cand_zip, -amndt_ind, -image_num, -zip_code, -employer, -occupation, -file_num, -memo_cd, -memo_text, -sub_id) %>%
  arrange(transaction_amt) %>% filter(transaction_amt > 0)
```

```{r}
RomneyPAC<- RomneyContributions %>%
  group_by(name, transaction_type)%>%
  summarise(PACcontribution = sum(transaction_amt)) %>%
  arrange(desc (PACcontribution))

RomneyPAC %>%
  ggplot(aes(x=name, y=PACcontribution)) + geom_bar(stat = "identity")
```

```{r}
ObamaContributions <- candidateContributions %>% filter(cand_id == "P80003338", entity_type=="PAC", cand_election_yr == "2012")%>%
  select(-cand_city, -cand_state, -cand_st1,-cand_st2, -cand_office_district, -cand_status, -cand_zip, -amndt_ind, -image_num, -zip_code, -employer, -occupation, -file_num, -memo_cd, -memo_text, -sub_id) %>%
  arrange(transaction_amt) %>% filter(transaction_amt > 0)

ObamaPAC <- ObamaContributions %>%
  group_by(name, transaction_type)%>%
  summarise(PACcontribution = sum(transaction_amt)) %>%
  arrange(desc (PACcontribution))

ObamaPAC %>%
  ggplot(aes(x=name, y=PACcontribution)) + geom_bar(stat = "identity")
```

