---
title: "Mini-Project 2"
author: "Kalynn Kosyka, Subashini Sridhar, Erina Fukuda"
date: "March 24, 2017"
output: html_document
---
## Loading the data
```{r, message=FALSE, warning=FALSE, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
```

```{r, message=FALSE, warning=FALSE}
candidateContributions<-candidates %>%
  left_join(contributions, by = c("cand_id" = "cand_id"))
```

```{r, message=FALSE, warning=FALSE}
#Assign cand_id to each candidate for ease of use later on
Romney="P80003353"
Obama="P80003338"

candidateContributions<-candidates %>%
  left_join(contributions, by = c("cand_id" = "cand_id"))

#Function to create data for contributions of each candidate
contributionsData <- function(id) {
	data <- candidateContributions %>%
	  filter(cand_id == id, entity_type=="PAC", cand_election_yr == "2012")%>%
  select(-cand_city, -cand_state, -cand_st1,-cand_st2, -cand_office_district, -cand_status, -cand_zip, -amndt_ind, -image_num, -zip_code, -employer, -occupation, -file_num, -memo_cd, -memo_text, -sub_id) %>%
  arrange(transaction_amt) %>% filter(transaction_amt > 0)
}

#Function to create data for Political Action Committee (PAC) for each candidate
PAC <- function(Contributions2) {
  Contributions2 %>%
  group_by(name,transaction_type)%>%
  summarise(PACcontribution = sum(transaction_amt)) %>%
  arrange(desc (PACcontribution))%>%
    mutate(transactionAmt = (if(transaction_type == "24A"){0-PACcontribution} else{PACcontribution}))
}

#Function to create a plot for PAC for each candidate
makePlot <- function(candidatePAC,name) {
  candidatePAC %>%
    ggplot(aes(x=name, y=transactionAmt, fill = transaction_type))+
    geom_bar(stat = "identity")+  
    labs(title = c("PAC Contribution towards ",name), x = "PAC", y = "Contribution Amount ($)")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
    scale_fill_manual(name = "Transaction Type", values = c("#D05955","#3B4C5D",   "#66AD9B"))
}

#Create `contributions` data set for Romney and Obama
RomneyContributions<-contributionsData(Romney)
ObamaContributions <- contributionsData(Obama)

#Create `PAC` data set for Romney and Obama
RomneyPAC <- PAC(RomneyContributions)
ObamaPAC <- PAC(ObamaContributions)
```
```


```{r fig.width=8, fig.height=20, message=FALSE, warning=FALSE}
#Create plots for RomneyPAC and ObamaPAC
makePlot(RomneyPAC, Romney)
makePlot(ObamaPAC, Obama)
```


##fix scale
```{r fig.width=4, fig.height=5, message=FALSE, warning=FALSE}

```